spring:
  kafka:
    consumer:
      group-id: notification-group-v100
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.value.default.type: org.example.dto.OrderRequest
        spring.json.trusted.packages: "*"


management:
  endpoints:
    web:
      exposure:
        include: health

server:
  port: 8080